// Copyright Voxel Plugin SAS, 2026. All Rights Reserved.

#include "Navigation/VoxelNavigationInvoker.h"
#include "VoxelDependency.h"
#include "VoxelTaskContext.h"
#include "VoxelInvalidationCallstack.h"
#include "SceneView.h"
#include "SceneManagement.h"
#include "NavigationSystem.h"

FVoxelNavigationInvokerView::FVoxelNavigationInvokerView(
	const int32 ChunkSize,
	const FTransform& LocalToWorld)
	: ChunkSize(ChunkSize)
	, LocalToWorld(LocalToWorld)
	, Dependency(FVoxelDependency::Create("FVoxelNavigationInvokerView"))
{
	ensure(ChunkSize > 0);
}

TVoxelFuture<const TVoxelSet<FIntVector>> FVoxelNavigationInvokerView::GetChunks(FVoxelDependencyCollector& DependencyCollector) const
{
	DependencyCollector.AddDependency(*Dependency);

	VOXEL_SCOPE_LOCK(CriticalSection);

	if (!Chunks_RequiresLock)
	{
		// Async to avoid recursive locks
		return Future.Then_AsyncThread(MakeStrongPtrLambda(this, [this]
		{
			VOXEL_SCOPE_LOCK(CriticalSection);
			return Chunks_RequiresLock.ToSharedRef();
		}));
	}

	return Chunks_RequiresLock.ToSharedRef();
}

void FVoxelNavigationInvokerView::Tick(const TArray<FNavigationInvokerRaw>& InvokerLocations)
{
	VOXEL_FUNCTION_COUNTER();

	if (!Future.IsComplete())
	{
		return;
	}

	VOXEL_SCOPE_COUNTER_FORMAT("InvokerLocations.Num() = %d", InvokerLocations.Num());

	TVoxelArray<FSphere> Invokers;
	Invokers.Reserve(InvokerLocations.Num());

	for (const FNavigationInvokerRaw& Invoker : InvokerLocations)
	{
		Invokers.Add(FSphere
		{
			Invoker.Location,
			Invoker.RadiusMax
		});
	}

	if (Invokers == LastInvokers)
	{
		VOXEL_SCOPE_LOCK(CriticalSection);
		if (!Chunks_RequiresLock)
		{
			Chunks_RequiresLock = MakeShared<TVoxelSet<FIntVector>>();
		}
		return;
	}

	LastInvokers = Invokers;

	ensure(Future.IsComplete());

	Future = Voxel::AsyncTask(MakeWeakPtrLambda(this, [this, Invokers = MakeSharedCopy(MoveTemp(Invokers))]
	{
		VOXEL_SCOPE_COUNTER("FVoxelNavigationInvokerView");

		const TSharedRef<TVoxelSet<FIntVector>> NewChunks = MakeShared<TVoxelSet<FIntVector>>();

		if (!FVoxelUtilities::ComputeInvokerChunks(
			*NewChunks,
			MoveTemp(*Invokers),
			LocalToWorld,
			ChunkSize,
			1024 * 1024))
		{
			VOXEL_MESSAGE(Error, "More than 1M chunks generated by Navigation invoker for chunk size {1}, abording", ChunkSize);
		}

		{
			VOXEL_SCOPE_LOCK(CriticalSection);

			if (!Chunks_RequiresLock)
			{
				// Initialization, don't invalidate dependency
				Chunks_RequiresLock = NewChunks;
				return;
			}

			if (NewChunks->OrderIndependentEqual(*Chunks_RequiresLock))
			{
				return;
			}

			Chunks_RequiresLock = NewChunks;
		}

		FVoxelInvalidationScope Scope("FVoxelNavigationInvokerView::Tick");
		Dependency->Invalidate();
	}));
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

TSharedRef<FVoxelNavigationInvokerView> FVoxelNavigationInvokerManager::MakeView(
	const int32 ChunkSize,
	const FTransform& LocalToWorld)
{
	VOXEL_FUNCTION_COUNTER();
	check(IsInGameThread());

	const TSharedRef<FVoxelNavigationInvokerView> View = MakeShared<FVoxelNavigationInvokerView>(
		ChunkSize,
		LocalToWorld);

	// Ensure the view is up to date in the first query
	if (const UNavigationSystemV1* NavSys = FNavigationSystem::GetCurrent<UNavigationSystemV1>(GetWorld().Resolve()))
	{
		FVoxelTaskScope Scope(*GVoxelGlobalTaskContext);
		View->Tick(NavSys->GetInvokerLocations());
	}
	else
	{
		FVoxelTaskScope Scope(*GVoxelGlobalTaskContext);
		View->Tick({});
	}

	WeakViews.Add(View);
	return View;
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

void FVoxelNavigationInvokerManager::Tick()
{
	VOXEL_FUNCTION_COUNTER();
	check(IsInGameThread());

	const double Time = FPlatformTime::Seconds();
	if (Time < LastTickTime + 0.05)
	{
		return;
	}
	LastTickTime = Time;

	const UNavigationSystemV1* NavSys = FNavigationSystem::GetCurrent<UNavigationSystemV1>(GetWorld().Resolve());
	for (auto It = WeakViews.CreateIterator(); It; ++It)
	{
		const TSharedPtr<FVoxelNavigationInvokerView> View = It->Pin();
		if (!View)
		{
			It.RemoveCurrent();
			continue;
		}

		if (NavSys)
		{
			View->Tick(NavSys->GetInvokerLocations());
		}
		else
		{
			View->Tick({});
		}
	}
}