// Copyright Voxel Plugin SAS, 2026. All Rights Reserved.

#include "VoxelISPCNodeHelpers.h"

REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Ceil_DoubleToDouble);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Ceil_DoubleToInt32);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Ceil_DoubleToInt64);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Ceil_FloatToFloat);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Ceil_FloatToInt32);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Ceil_FloatToInt64);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Floor_DoubleToDouble);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Floor_DoubleToInt32);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Floor_DoubleToInt64);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Floor_FloatToFloat);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Floor_FloatToInt32);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Floor_FloatToInt64);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Round_DoubleToDouble);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Round_DoubleToInt32);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Round_DoubleToInt64);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Round_FloatToFloat);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Round_FloatToInt32);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelComputeNode_Round_FloatToInt64);