// Copyright Voxel Plugin SAS, 2026. All Rights Reserved.

#include "VoxelISPCNodeHelpers.h"

REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_CrossProduct_2D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_CrossProduct_2D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_CrossProduct_3D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_CrossProduct_3D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Distance2D_3D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Distance2D_3D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Distance_2D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Distance_2D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Distance_3D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Distance_3D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_DotProduct_2D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_DotProduct_2D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_DotProduct_3D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_DotProduct_3D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Length_2D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Length_2D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Length_3D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Length_3D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_LengthXY_3D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_LengthXY_3D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Normalize_2D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Normalize_2D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Normalize_3D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_Normalize_3D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_NormalToSlope_2D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_NormalToSlope_2D_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_NormalToSlope_3D_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelVectorNodes, VoxelComputeNode_NormalToSlope_3D_Float);