// Copyright Voxel Plugin SAS, 2026. All Rights Reserved.

#include "VoxelGraphNode_CallFunction.h"
#include "VoxelGraph.h"
#include "VoxelEdGraph.h"
#include "VoxelGraphToolkit.h"
#include "VoxelGraphTracker.h"
#include "VoxelTerminalGraph.h"
#include "VoxelFunctionLibraryAsset.h"
#include "Nodes/VoxelGraphNode_FunctionInput.h"

void UVoxelGraphNode_CallFunctionBase::AllocateDefaultPins()
{
	VOXEL_FUNCTION_COUNTER();

	ON_SCOPE_EXIT
	{
		Super::AllocateDefaultPins();
	};

	const UVoxelTerminalGraph* BaseTerminalGraph = GetBaseTerminalGraph();

	OnChangedPtr = MakeSharedVoid();

	AddPins();

	if (!BaseTerminalGraph)
	{
		return;
	}

	const FOnVoxelGraphChanged InputOrOutputChanged = FOnVoxelGraphChanged::Make(OnChangedPtr, this, [this]
	{
		ReconstructNode();
	});

	GVoxelGraphTracker->OnInputChanged(*BaseTerminalGraph).Add(InputOrOutputChanged);
	GVoxelGraphTracker->OnOutputChanged(*BaseTerminalGraph).Add(InputOrOutputChanged);
	GVoxelGraphTracker->OnTerminalGraphMetaDataChanged(*BaseTerminalGraph).Add(FOnVoxelGraphChanged::Make(OnChangedPtr, this, [this]
	{
		RefreshNode();
	}));

	PinNameToIsOptional.Reset();

	for (const FGuid& Guid : BaseTerminalGraph->GetFunctionInputs())
	{
		const FVoxelGraphFunctionInput& Input = BaseTerminalGraph->FindInputChecked(Guid);
		const FName PinUniqueName = *Guid.ToString();

		UEdGraphPin* GraphPin = CreatePin(
			EGPD_Input,
			Input.Type.GetEdGraphPinType(),
			PinUniqueName);

		GraphPin->PinFriendlyName = FText::FromName(Input.Name);

		const bool bHasDefaultNode = INLINE_LAMBDA
		{
			for (const UEdGraphNode* Node : BaseTerminalGraph->GetEdGraph().Nodes)
			{
				const UVoxelGraphNode_FunctionInputDefault* InputDefaultNode = Cast<UVoxelGraphNode_FunctionInputDefault>(Node);
				if (InputDefaultNode &&
					InputDefaultNode->Guid == Guid)
				{
					return true;
				}
			}

			return false;
		};

		const bool bOptionalValue =
			!Input.bNoDefault &&
			!Input.Type.HasPinDefaultValue();

		PinNameToIsOptional.Add_EnsureNew(GraphPin->PinName, bHasDefaultNode || bOptionalValue);

		if (bHasDefaultNode ||
			Input.bNoDefault ||
			!Input.Type.HasPinDefaultValue())
		{
			continue;
		}

		Input.DefaultPinValue.ApplyToPinDefaultValue(*GraphPin);
		GraphPin->AutogeneratedDefaultValue = GraphPin->DefaultValue;
	}

	for (const FGuid& Guid : BaseTerminalGraph->GetFunctionOutputs())
	{
		const FVoxelGraphFunctionOutput& Output = BaseTerminalGraph->FindOutputChecked(Guid);
		const FName PinUniqueName = *Guid.ToString();

		UEdGraphPin* GraphPin = CreatePin(
			EGPD_Output,
			Output.Type.GetEdGraphPinType(),
			PinUniqueName);

		GraphPin->PinFriendlyName = FText::FromName(Output.Name);
	}
}

FText UVoxelGraphNode_CallFunctionBase::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	const UVoxelTerminalGraph* BaseTerminalGraph = GetBaseTerminalGraph();
	if (!BaseTerminalGraph)
	{
		return INVTEXT("Empty");
	}

	return FText::FromString(BaseTerminalGraph->GetDisplayName());
}

FLinearColor UVoxelGraphNode_CallFunctionBase::GetNodeTitleColor() const
{
	return FLinearColor::Gray;
}

FText UVoxelGraphNode_CallFunctionBase::GetTooltipText() const
{
	const UVoxelTerminalGraph* BaseTerminalGraph = GetBaseTerminalGraph();
	if (!BaseTerminalGraph)
	{
		return {};
	}

	FString Description = BaseTerminalGraph->GetMetadata().Description;
	if (!Description.IsEmpty())
	{
		Description += "\n\n";
	}
	Description += "GUID: " + BaseTerminalGraph->GetGuid().ToString(EGuidFormats::DigitsWithHyphens);

	return FText::FromString(Description);
}

FSlateIcon UVoxelGraphNode_CallFunctionBase::GetIconAndTint(FLinearColor& OutColor) const
{
	return FSlateIcon("EditorStyle", "GraphEditor.Function_16x");
}

bool UVoxelGraphNode_CallFunctionBase::IsPinOptional(const UEdGraphPin& Pin) const
{
	if (Pin.Direction == EGPD_Output ||
		Pin.ParentPin)
	{
		return false;
	}

	const bool* IsOptionalPtr = PinNameToIsOptional.Find(Pin.PinName);
	if (!ensure(IsOptionalPtr))
	{
		return false;
	}

	return *IsOptionalPtr;
}

bool UVoxelGraphNode_CallFunctionBase::ShouldHidePinDefaultValue(const UEdGraphPin& Pin) const
{
	if (Pin.Direction == EGPD_Output ||
		Pin.ParentPin)
	{
		return false;
	}

	const bool* IsOptionalPtr = PinNameToIsOptional.Find(Pin.PinName);
	if (!ensure(IsOptionalPtr))
	{
		return false;
	}

	if (*IsOptionalPtr)
	{
		return true;
	}

	const UVoxelTerminalGraph* TerminalGraph = GetBaseTerminalGraph();
	if (!TerminalGraph)
	{
		return false;
	}

	FGuid Guid;
	if (!FGuid::Parse(Pin.PinName.ToString(), Guid))
	{
		return false;
	}

	const FVoxelGraphFunctionInput* Input = TerminalGraph->FindInput(Guid);
	if (!Input)
	{
		return false;
	}

	return Input->bNoDefault;
}

void UVoxelGraphNode_CallFunctionBase::JumpToDefinition() const
{
	const UVoxelTerminalGraph* BaseTerminalGraph = GetBaseTerminalGraph();
	if (!BaseTerminalGraph)
	{
		return;
	}

	FVoxelUtilities::FocusObject(BaseTerminalGraph);
}

void UVoxelGraphNode_CallFunctionBase::PostReconstructNode()
{
	Super::PostReconstructNode();

	// Old Run Execution pin
	if (UEdGraphPin* Pin = FindPin(TEXT("ORPHANED_EnableNode")))
	{
		RemovePin(Pin);
	}
}

FName UVoxelGraphNode_CallFunctionBase::GetPinCategory(const UEdGraphPin& Pin) const
{
	FGuid Guid;
	if (!ensure(FGuid::Parse(Pin.GetName(), Guid)))
	{
		return {};
	}

	const UVoxelTerminalGraph* BaseTerminalGraph = GetBaseTerminalGraph();
	if (!ensure(BaseTerminalGraph))
	{
		return {};
	}

	if (Pin.Direction == EGPD_Input)
	{
		const FVoxelGraphFunctionInput* Input = BaseTerminalGraph->FindInput(Guid);
		if (!ensure(Input))
		{
			return {};
		}

		return *Input->Category;
	}
	else
	{
		check(Pin.Direction == EGPD_Output);

		const FVoxelGraphFunctionOutput* Output = BaseTerminalGraph->FindOutput(Guid);
		if (!ensure(Output))
		{
			return {};
		}

		return *Output->Category;
	}
}

TSharedRef<IVoxelNodeDefinition> UVoxelGraphNode_CallFunctionBase::GetNodeDefinition()
{
	return MakeShared<FVoxelNodeDefinition_CallFunctionBase>(*this);
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

TSharedPtr<const IVoxelNodeDefinition::FNode> FVoxelNodeDefinition_CallFunctionBase::GetInputs() const
{
	const TSharedRef<FCategoryNode> RootNode = FNode::MakeRoot(true);

	const UVoxelTerminalGraph* BaseTerminalGraph = Node.GetBaseTerminalGraph();
	if (!BaseTerminalGraph)
	{
		return RootNode;
	}

	for (const FGuid& Guid : BaseTerminalGraph->GetFunctionInputs())
	{
		RootNode->FindOrAddCategory(BaseTerminalGraph->FindInputChecked(Guid).Category)->AddPin(FName(Guid.ToString()));
	}

	return RootNode;
}

TSharedPtr<const IVoxelNodeDefinition::FNode> FVoxelNodeDefinition_CallFunctionBase::GetOutputs() const
{
	const TSharedRef<FCategoryNode> RootNode = FNode::MakeRoot(false);

	const UVoxelTerminalGraph* BaseTerminalGraph = Node.GetBaseTerminalGraph();
	if (!BaseTerminalGraph)
	{
		return RootNode;
	}

	for (const FGuid& Guid : BaseTerminalGraph->GetFunctionOutputs())
	{
		RootNode->FindOrAddCategory(BaseTerminalGraph->FindOutputChecked(Guid).Category)->AddPin(FName(Guid.ToString()));
	}

	return RootNode;
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

const UVoxelTerminalGraph* UVoxelGraphNode_CallMemberFunction::GetBaseTerminalGraph() const
{
	const UVoxelGraph* Graph = GetTypedOuter<UVoxelGraph>();
	if (!ensure(Graph))
	{
		return nullptr;
	}

	if (!bCallParent)
	{
		return Graph->FindTerminalGraph(Guid);
	}

	const UVoxelGraph* BaseGraph = Graph->GetBaseGraph_Unsafe();
	if (!BaseGraph)
	{
		return nullptr;
	}

	return BaseGraph->FindTerminalGraph(Guid);
}

void UVoxelGraphNode_CallMemberFunction::AllocateDefaultPins()
{
	if (const UVoxelTerminalGraph* BaseTerminalGraph = GetBaseTerminalGraph())
	{
		CachedName = BaseTerminalGraph->GetDisplayName();

		OnFunctionMetaDataChangedPtr = MakeSharedVoid();
		GVoxelGraphTracker->OnTerminalGraphMetaDataChanged(*BaseTerminalGraph).Add(FOnVoxelGraphChanged::Make(OnFunctionMetaDataChangedPtr, this, [=, this]
		{
			RefreshNode();
		}));
	}

	Super::AllocateDefaultPins();
}

FText UVoxelGraphNode_CallMemberFunction::GetNodeTitle(const ENodeTitleType::Type TitleType) const
{
	if (!GetBaseTerminalGraph())
	{
		return FText::FromString(CachedName);
	}

	if (!bCallParent)
	{
		return Super::GetNodeTitle(TitleType);
	}

	return FText::FromString("Call Parent: " + Super::GetNodeTitle(TitleType).ToString());
}

FLinearColor UVoxelGraphNode_CallMemberFunction::GetNodeTitleColor() const
{
	if (bCallParent)
	{
		return GetDefault<UGraphEditorSettings>()->ParentFunctionCallNodeTitleColor;
	}

	return Super::GetNodeTitleColor();
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

void UVoxelGraphNode_CallMemberFunction::PrepareForCopying()
{
	Super::PrepareForCopying();

	if (GetBaseTerminalGraph())
	{
		CachedName = GetNodeTitle(ENodeTitleType::FullTitle).ToString();
	}
}

void UVoxelGraphNode_CallMemberFunction::PostPasteNode()
{
	Super::PostPasteNode();

	UVoxelGraph* Graph = GetTypedOuter<UVoxelGraph>();
	if (!ensure(Graph))
	{
		return;
	}

	if (Graph->FindTerminalGraph(Guid))
	{
		return;
	}

	// Try to find a matching name
	for (const FGuid& TerminalGraphGuid : Graph->GetTerminalGraphs())
	{
		const UVoxelTerminalGraph& TerminalGraph = Graph->FindTerminalGraphChecked(TerminalGraphGuid);
		if (TerminalGraph.GetDisplayName() != CachedName)
		{
			continue;
		}

		Guid = TerminalGraphGuid;
		return;
	}
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

const UVoxelTerminalGraph* UVoxelGraphNode_CallExternalFunction::GetBaseTerminalGraph() const
{
	if (!FunctionLibrary)
	{
		return nullptr;
	}

	return FunctionLibrary->GetGraph().FindTerminalGraph(Guid);
}

void UVoxelGraphNode_CallExternalFunction::AllocateDefaultPins()
{
	if (const UVoxelTerminalGraph* BaseTerminalGraph = GetBaseTerminalGraph())
	{
		CachedName = BaseTerminalGraph->GetDisplayName();

		OnFunctionMetaDataChangedPtr = MakeSharedVoid();
		GVoxelGraphTracker->OnTerminalGraphMetaDataChanged(*BaseTerminalGraph).Add(FOnVoxelGraphChanged::Make(OnFunctionMetaDataChangedPtr, this, [=, this]
		{
			RefreshNode();
		}));
	}

	Super::AllocateDefaultPins();
}

FText UVoxelGraphNode_CallExternalFunction::GetNodeTitle(const ENodeTitleType::Type TitleType) const
{
	if (GetBaseTerminalGraph())
	{
		return Super::GetNodeTitle(TitleType);
	}

	return FText::FromString(CachedName);
}

bool UVoxelGraphNode_CallExternalFunction::CanPasteHere(const UEdGraph* TargetGraph) const
{
	if (!Super::CanPasteHere(TargetGraph))
	{
		return false;
	}

	if (!ensure(FunctionLibrary))
	{
		return false;
	}

	const UVoxelEdGraph* VoxelGraph = Cast<UVoxelEdGraph>(TargetGraph);
	if (!VoxelGraph)
	{
		return false;
	}

	const TSharedPtr<FVoxelGraphToolkit> Toolkit = VoxelGraph->GetGraphToolkit();
	if (!Toolkit ||
		!Toolkit->Asset)
	{
		return false;
	}

	return FunctionLibrary->GetGraph().FindTerminalGraph(Guid)->CanBePlaced(*Toolkit->Asset);
}