// Copyright Voxel Plugin SAS, 2026. All Rights Reserved.

#pragma once

#include "VoxelMinimal.h"
#include "VoxelAssetIcon.h"
#include "VoxelLayerStack.generated.h"

class UVoxelHeightLayer;
class UVoxelVolumeLayer;

UCLASS(BlueprintType, meta = (VoxelAssetType, AssetColor=Grey))
class VOXEL_API UVoxelLayerStack : public UVoxelAsset
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Config", meta = (ForceShowPluginContent))
	TArray<TObjectPtr<UVoxelHeightLayer>> HeightLayers;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Config", meta = (ForceShowPluginContent))
	TArray<TObjectPtr<UVoxelVolumeLayer>> VolumeLayers;

	// How far up & how far down to extend the distance field generated by height layers
	// Keeping this low helps generate fewer chunks
	UPROPERTY(EditAnywhere, Category = "Config")
	float MaxDistance = 100000.f;

#if WITH_EDITORONLY_DATA
	UPROPERTY(EditAnywhere, Category = "Editor")
	FVoxelAssetIcon AssetIcon;
#endif

public:
	static FSimpleMulticastDelegate OnChanged;

	UVoxelLayerStack();

	static UVoxelLayerStack* Default();

	//~ Begin UObject Interface
	virtual void PostLoad() override;
	virtual void Serialize(FArchive& Ar) override;
#if WITH_EDITOR
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
#endif
	//~ End UObject Interface
};