# Audit UI All - Run all UI audits and generate comprehensive report
#
# Run in UE Editor: py "D:/UEProjects/MO57/Content/Python/audit_ui_all.py"
#
# This master script runs all UI audits:
# - Widget audit (common elements)
# - Layout audit (dimensions, anchors)
# - Style audit (colors, fonts)
# - Validation (issues and fixes)
#
# REQUIRES: MOWidgetEditorUtils C++ utility
# Output: D:/UEProjects/MO57/Content/Python/audit_output/comprehensive_report.txt

print("=== COMPREHENSIVE UI AUDIT LOADING ===")
import unreal
from collections import defaultdict
import os

OUTPUT_DIR = "D:/UEProjects/MO57/Content/Python/audit_output"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "comprehensive_report.txt")
os.makedirs(OUTPUT_DIR, exist_ok=True)

_output_lines = []

def log(msg):
    print(f"[AUDIT] {msg}")
    _output_lines.append(msg)

def write_output():
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(_output_lines))
    print(f"[AUDIT] Output written to: {OUTPUT_FILE}")

def get_all_widget_blueprints():
    asset_registry = unreal.AssetRegistryHelpers.get_asset_registry()
    filter = unreal.ARFilter(
        class_names=["WidgetBlueprint"],
        package_paths=["/MOFramework"],
        recursive_paths=True
    )
    assets = asset_registry.get_assets(filter)
    return [str(asset.package_name) for asset in assets]

def color_to_hex(color):
    r = int(min(255, max(0, color.r * 255)))
    g = int(min(255, max(0, color.g * 255)))
    b = int(min(255, max(0, color.b * 255)))
    return f"#{r:02X}{g:02X}{b:02X}"

def get_anchor_preset_name(min_x, min_y, max_x, max_y):
    presets = {
        (0.0, 0.0, 0.0, 0.0): "TopLeft",
        (0.5, 0.0, 0.5, 0.0): "TopCenter",
        (1.0, 0.0, 1.0, 0.0): "TopRight",
        (0.0, 0.5, 0.0, 0.5): "CenterLeft",
        (0.5, 0.5, 0.5, 0.5): "Center",
        (1.0, 0.5, 1.0, 0.5): "CenterRight",
        (0.0, 1.0, 0.0, 1.0): "BottomLeft",
        (0.5, 1.0, 0.5, 1.0): "BottomCenter",
        (1.0, 1.0, 1.0, 1.0): "BottomRight",
        (0.0, 0.0, 1.0, 1.0): "FullScreen",
    }
    key = (round(min_x, 1), round(min_y, 1), round(max_x, 1), round(max_y, 1))
    return presets.get(key, f"Custom")

def run():
    log("=" * 80)
    log("COMPREHENSIVE UI AUDIT REPORT")
    log("=" * 80)
    log("Generated by MOWidgetEditorUtils")

    if not hasattr(unreal, 'MOWidgetEditorUtils'):
        log("\nERROR: MOWidgetEditorUtils not found!")
        log("Please compile the MOFramework module first.")
        return

    wbp_paths = get_all_widget_blueprints()
    log(f"\nAnalyzing {len(wbp_paths)} Widget Blueprints...")

    # Collect data from all blueprints
    all_widgets = []
    all_layouts = []
    all_styles = []
    all_issues = []
    blueprint_summaries = []

    for path in wbp_paths:
        wbp = unreal.EditorAssetLibrary.load_asset(path)
        if not wbp:
            continue

        bp_name = path.split('/')[-1]

        # Get all widget names
        widget_names = unreal.MOWidgetEditorUtils.get_all_widget_names(wbp)
        root_type = unreal.MOWidgetEditorUtils.get_root_widget_type(wbp)

        # Get layout info
        layouts = unreal.MOWidgetEditorUtils.get_all_widget_layout_info(wbp)
        for layout in layouts:
            all_layouts.append({
                'blueprint': bp_name,
                'name': str(layout.name),
                'type': str(layout.widget_type),
                'is_variable': layout.is_variable,
                'anchor_preset': get_anchor_preset_name(
                    layout.anchor_min_x, layout.anchor_min_y,
                    layout.anchor_max_x, layout.anchor_max_y
                ),
                'size_x': layout.offset_right if abs(layout.anchor_min_x - layout.anchor_max_x) < 0.01 else None,
                'size_y': layout.offset_bottom if abs(layout.anchor_min_y - layout.anchor_max_y) < 0.01 else None,
            })
            all_widgets.append({
                'blueprint': bp_name,
                'name': str(layout.name),
                'type': str(layout.widget_type),
                'is_variable': layout.is_variable,
            })

        # Get styles
        styles = unreal.MOWidgetEditorUtils.extract_widget_styles(wbp)
        for style in styles:
            if style.has_text_style:
                all_styles.append({
                    'blueprint': bp_name,
                    'widget': str(style.widget_name),
                    'type': 'text',
                    'font_size': style.font_size,
                    'color': color_to_hex(style.text_color),
                })

        # Get validation issues
        issues = unreal.MOWidgetEditorUtils.validate_widget_blueprint(wbp)
        for issue in issues:
            all_issues.append({
                'blueprint': bp_name,
                'severity': str(issue.severity),
                'widget': str(issue.widget_name),
                'message': str(issue.message),
            })

        blueprint_summaries.append({
            'name': bp_name,
            'path': path,
            'root_type': root_type,
            'widget_count': len(widget_names),
            'issue_count': len([i for i in issues if str(i.severity) in ['Error', 'Warning']]),
        })

    # ========================================
    # EXECUTIVE SUMMARY
    # ========================================
    log(f"\n" + "=" * 80)
    log("EXECUTIVE SUMMARY")
    log("=" * 80)

    total_widgets = len(all_widgets)
    total_issues = len([i for i in all_issues if i['severity'] in ['Error', 'Warning']])
    non_variable = len([w for w in all_widgets if not w['is_variable']])

    log(f"\n  Blueprints: {len(wbp_paths)}")
    log(f"  Total Widgets: {total_widgets}")
    log(f"  Widgets not marked as variables: {non_variable}")
    log(f"  Validation issues (Error/Warning): {total_issues}")

    # ========================================
    # COMMON WIDGETS (for consolidation)
    # ========================================
    log(f"\n" + "=" * 80)
    log("COMMON WIDGETS (Consolidation Candidates)")
    log("=" * 80)

    widget_by_name = defaultdict(list)
    for w in all_widgets:
        widget_by_name[w['name']].append(w['blueprint'])

    common = sorted(widget_by_name.items(), key=lambda x: -len(x[1]))
    log("\n  Widgets appearing in 3+ blueprints:")
    for name, bps in common[:20]:
        if len(bps) >= 3:
            log(f"    {name}: {len(bps)} blueprints")

    # ========================================
    # LAYOUT PATTERNS
    # ========================================
    log(f"\n" + "=" * 80)
    log("LAYOUT PATTERNS")
    log("=" * 80)

    # Common sizes
    size_counts = defaultdict(list)
    for l in all_layouts:
        if l['size_x'] and l['size_y'] and l['size_x'] > 0 and l['size_y'] > 0:
            key = (round(l['size_x']/10)*10, round(l['size_y']/10)*10)
            size_counts[key].append(f"{l['blueprint']}:{l['name']}")

    log("\n  Common Widget Sizes:")
    for (w, h), widgets in sorted(size_counts.items(), key=lambda x: -len(x[1]))[:10]:
        if len(widgets) >= 2:
            log(f"    ~{w}x{h}: {len(widgets)} widgets")

    # Common anchors
    anchor_counts = defaultdict(int)
    for l in all_layouts:
        if l['anchor_preset'] != 'Custom':
            anchor_counts[l['anchor_preset']] += 1

    log("\n  Anchor Usage:")
    for anchor, count in sorted(anchor_counts.items(), key=lambda x: -x[1]):
        log(f"    {anchor}: {count}")

    # ========================================
    # STYLE PATTERNS
    # ========================================
    log(f"\n" + "=" * 80)
    log("STYLE PATTERNS")
    log("=" * 80)

    # Font sizes
    font_sizes = defaultdict(int)
    for s in all_styles:
        if s['type'] == 'text':
            font_sizes[int(s['font_size'])] += 1

    log("\n  Font Size Distribution:")
    for size, count in sorted(font_sizes.items()):
        log(f"    {size}pt: {count} widgets")

    # Colors
    colors = defaultdict(int)
    for s in all_styles:
        if s['type'] == 'text':
            colors[s['color']] += 1

    log("\n  Text Color Usage:")
    for color, count in sorted(colors.items(), key=lambda x: -x[1])[:10]:
        log(f"    {color}: {count} widgets")

    # ========================================
    # VALIDATION ISSUES
    # ========================================
    log(f"\n" + "=" * 80)
    log("VALIDATION ISSUES")
    log("=" * 80)

    errors = [i for i in all_issues if i['severity'] == 'Error']
    warnings = [i for i in all_issues if i['severity'] == 'Warning']

    log(f"\n  Errors: {len(errors)}")
    log(f"  Warnings: {len(warnings)}")

    if warnings:
        log("\n  Warnings by type:")
        warning_types = defaultdict(list)
        for w in warnings:
            warning_types[w['message']].append(f"{w['blueprint']}:{w['widget']}")

        for msg, locations in sorted(warning_types.items(), key=lambda x: -len(x[1])):
            log(f"\n    {msg}")
            log(f"    ({len(locations)} occurrences)")

    # ========================================
    # ACTION ITEMS
    # ========================================
    log(f"\n" + "=" * 80)
    log("ACTION ITEMS")
    log("=" * 80)

    log("\n  1. MARK WIDGETS AS VARIABLES:")
    log("     Run: py \"D:/UEProjects/MO57/Content/Python/batch_ui_operations.py\"")

    log("\n  2. CREATE BASE CLASSES FOR:")
    common_3plus = [name for name, bps in common if len(bps) >= 3]
    if common_3plus:
        log(f"     Common bindings: {', '.join(common_3plus[:10])}")

    log("\n  3. STANDARDIZE STYLES:")
    if font_sizes:
        log(f"     Font sizes to consolidate: {sorted(font_sizes.keys())}")
    if colors:
        log(f"     Colors to consolidate: {len(colors)} unique colors -> aim for 5-10")

    log("\n  4. FIX VALIDATION WARNINGS:")
    log(f"     {len(warnings)} warnings to address")

    # ========================================
    # PER-BLUEPRINT SUMMARY
    # ========================================
    log(f"\n" + "=" * 80)
    log("PER-BLUEPRINT SUMMARY")
    log("=" * 80)

    # Sort by issue count descending
    for bp in sorted(blueprint_summaries, key=lambda x: -x['issue_count']):
        status = "OK" if bp['issue_count'] == 0 else f"{bp['issue_count']} issues"
        log(f"  {bp['name']}: {bp['widget_count']} widgets, {status}")

    log(f"\n" + "=" * 80)
    log("COMPREHENSIVE AUDIT COMPLETE")
    log("=" * 80)
    log(f"\nDetailed reports available in {OUTPUT_DIR}/")
    log("  - layout_audit.txt")
    log("  - style_audit.txt")
    log("  - validation_report.txt")

print("[AUDIT] Starting comprehensive audit...")
try:
    run()
    write_output()
except Exception as e:
    print(f"[AUDIT ERROR] {e}")
    _output_lines.append(f"ERROR: {e}")
    import traceback
    traceback.print_exc()
    try:
        write_output()
    except:
        pass
print("[AUDIT] Finished.")
