<#
.SYNOPSIS
    Generates MOBuildInfoGenerated.h from current git state.

.DESCRIPTION
    Writes a small header into the MOFramework plugin that the C++
    FMOBuildInfo class reads. Hooked into MOFramework.Build.cs as a
    PreBuildStep so the displayed commit hash matches the build.

    Always overwrites the file. Safe to run with no git available — falls
    back to "unknown" sentinel values that the existing stub already uses.

.NOTES
    Invoked automatically by UnrealBuildTool. Can also be run manually:
        powershell.exe -ExecutionPolicy Bypass -File Tools/Update-BuildInfo.ps1
#>

[CmdletBinding()]
param(
    [string]$OutputPath = ''
)

$ErrorActionPreference = 'Stop'

# Resolve default output path now that $PSScriptRoot is populated. Doing
# this in the param default expression doesn't work — that scope evaluates
# before the script's automatic variables are bound.
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = [System.IO.Path]::GetFullPath((Join-Path $ScriptDir '..'))

if ([string]::IsNullOrEmpty($OutputPath)) {
    $OutputPath = Join-Path $ProjectRoot 'Plugins\MOFramework\Source\MOFramework\Public\MOBuildInfoGenerated.h'
}

function Invoke-GitOrFallback {
    # NOTE: don't name the parameter $Args — that's a PowerShell automatic
    # variable, the binder reassigns it and the call falls through with no
    # arguments. Renamed to $GitArgs to avoid the trap.
    param([string]$GitArgs, [string]$RepoPath, [string]$Fallback = 'unknown')

    try {
        # `git -C <path>` anchors git to the project repo regardless of where
        # UnrealBuildTool invoked us from. Without it the script queries
        # whatever happens to be in CWD (e.g. a sibling worktree).
        $allArgs = @('-C', $RepoPath) + $GitArgs.Split(' ')
        $output = & git $allArgs 2>$null
        if ($LASTEXITCODE -eq 0 -and $output) {
            return $output.Trim()
        }
    } catch { }
    return $Fallback
}

# Resolve git state against the project root. All branches fall through to
# a sentinel rather than failing — a missing-git build still produces a
# valid header.
$Hash      = Invoke-GitOrFallback -GitArgs 'rev-parse --short HEAD'        -RepoPath $ProjectRoot
$LongHash  = Invoke-GitOrFallback -GitArgs 'rev-parse HEAD'                -RepoPath $ProjectRoot
$Branch    = Invoke-GitOrFallback -GitArgs 'rev-parse --abbrev-ref HEAD'   -RepoPath $ProjectRoot
$Date      = Invoke-GitOrFallback -GitArgs 'show -s --format=%ci HEAD'     -RepoPath $ProjectRoot

# Dirty check — non-empty status output means uncommitted changes.
$IsDirty = '0'
try {
    $status = & git -C $ProjectRoot status --porcelain 2>$null
    if ($LASTEXITCODE -eq 0 -and $status) {
        $IsDirty = '1'
    }
} catch { }

# Resolve the output path relative to where the script lives so it works
# from any CWD (UBT may invoke us from the engine's working dir).
$OutputPath = [System.IO.Path]::GetFullPath($OutputPath)
$OutputDir = Split-Path $OutputPath -Parent
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Force $OutputDir | Out-Null
}

# Use ISO 8601 build timestamp so the displayed string is stable across locales.
$BuildStamp = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')

$Body = @"
// =============================================================================
// MOBuildInfoGenerated.h — AUTO-GENERATED by Tools/Update-BuildInfo.ps1
//
// DO NOT EDIT BY HAND. Overwritten on every build via MOFramework.Build.cs
// PreBuildSteps. The C++ FMOBuildInfo class includes this header to expose
// the values to Blueprint and to the main menu version label.
//
// If git is unavailable at build time (CI without checkout, source-only
// distribution, etc.), the values fall through to "unknown" — the C++ side
// treats those as "no version available" and hides the label.
// =============================================================================

#pragma once

#define MO_BUILD_COMMIT_HASH       "$Hash"
#define MO_BUILD_COMMIT_HASH_LONG  "$LongHash"
#define MO_BUILD_BRANCH            "$Branch"
#define MO_BUILD_COMMIT_DATE       "$Date"
#define MO_BUILD_DIRTY             $IsDirty
#define MO_BUILD_TIMESTAMP         "$BuildStamp"
"@

# Use UTF-8 (no BOM) to match the rest of the C++ headers.
[System.IO.File]::WriteAllText($OutputPath, $Body, [System.Text.UTF8Encoding]::new($false))

Write-Host "[BuildInfo] Wrote $OutputPath"
Write-Host "[BuildInfo]   commit=$Hash branch=$Branch dirty=$IsDirty"
