// Copyright Voxel Plugin SAS, 2026. All Rights Reserved.

#include "Collision/VoxelCollisionInvoker.h"
#include "VoxelWorld.h"
#include "VoxelState.h"
#include "VoxelRuntime.h"
#include "VoxelDependency.h"
#include "VoxelTaskContext.h"
#include "VoxelInvalidationCallstack.h"
#include "Collision/VoxelInvokerCollisionSubsystem.h"
#include "SceneView.h"
#include "SceneManagement.h"
#include "PrimitiveSceneProxy.h"

VOXEL_CONSOLE_VARIABLE(
	VOXEL_API, bool, GVoxelShowCollisionInvokers, false,
	"voxel.collision.ShowInvokers",
	"Show collision invokers");

VOXEL_CONSOLE_WORLD_COMMAND(
	"voxel.collision.LogInvokers",
	"Log collision invokers")
{
	FVoxelCollisionInvokerManager::Get(World)->LogInvokers();
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

FVoxelCollisionInvokerView::FVoxelCollisionInvokerView(
	const int32 ChunkSize,
	const FTransform& LocalToWorld)
	: ChunkSize(ChunkSize)
	, LocalToWorld(LocalToWorld)
	, Dependency(FVoxelDependency::Create("FVoxelCollisionInvokerView"))
{
	ensure(ChunkSize > 0);
}

TVoxelFuture<const TVoxelSet<FIntVector>> FVoxelCollisionInvokerView::GetChunks(FVoxelDependencyCollector& DependencyCollector) const
{
	DependencyCollector.AddDependency(*Dependency);

	VOXEL_SCOPE_LOCK(CriticalSection);

	if (!Chunks_RequiresLock)
	{
		// Async to avoid recursive locks
		return Future.Then_AsyncThread(MakeStrongPtrLambda(this, [this]
		{
			VOXEL_SCOPE_LOCK(CriticalSection);
			return Chunks_RequiresLock.ToSharedRef();
		}));
	}

	return Chunks_RequiresLock.ToSharedRef();
}

void FVoxelCollisionInvokerView::Tick(const TVoxelSet<UVoxelCollisionInvokerComponent*>& InvokerComponents)
{
	VOXEL_FUNCTION_COUNTER();

	if (!Future.IsComplete())
	{
		return;
	}

	VOXEL_SCOPE_COUNTER_FORMAT("InvokerComponents.Num() = %d", InvokerComponents.Num());

	TVoxelArray<FSphere> Invokers;
	Invokers.Reserve(InvokerComponents.Num());

#if !UE_BUILD_SHIPPING
	TVoxelArray<TVoxelObjectPtr<const UVoxelCollisionInvokerComponent>> NewInvokerComponents;
	NewInvokerComponents.Reserve(InvokerComponents.Num());
#endif

	for (const UVoxelCollisionInvokerComponent* InvokerComponent : InvokerComponents)
	{
		if (!ensure(InvokerComponent) ||
			!InvokerComponent->bEnabled)
		{
			continue;
		}

#if !UE_BUILD_SHIPPING
		NewInvokerComponents.Add(InvokerComponent);
#endif

		Invokers.Add(FSphere
		{
			InvokerComponent->GetComponentLocation(),
			InvokerComponent->Radius
		});
	}

	if (Invokers == LastInvokers)
	{
		VOXEL_SCOPE_LOCK(CriticalSection);
		if (!Chunks_RequiresLock)
		{
			Chunks_RequiresLock = MakeShared<TVoxelSet<FIntVector>>();
		}
		return;
	}

	FString ComponentChanges = "FVoxelCollisionInvokerView changed:";
#if VOXEL_INVALIDATION_TRACKING
	if (NewInvokerComponents == LastInvokerComponents)
	{
		check(Invokers.Num() == LastInvokers.Num());

		for (int32 Index = 0; Index < LastInvokers.Num(); Index++)
		{
			if (LastInvokers[Index] == Invokers[Index])
			{
				continue;
			}

			const UVoxelCollisionInvokerComponent* InvokerComponent = NewInvokerComponents[Index].Resolve();
			if (!ensureVoxelSlow(InvokerComponent))
			{
				continue;
			}

			ComponentChanges += "\n\t" + InvokerComponent->GetPathName() + ": " + LexToString(LastInvokers[Index]) + " -> " + LexToString(Invokers[Index]);
		}
	}
	else
	{
		const TVoxelSet<TVoxelObjectPtr<const UVoxelCollisionInvokerComponent>> NewInvokerComponentsSet(NewInvokerComponents);
		const TVoxelSet<TVoxelObjectPtr<const UVoxelCollisionInvokerComponent>> LastInvokerComponentsSet(LastInvokerComponents);

		for (const TVoxelObjectPtr<const UVoxelCollisionInvokerComponent> InvokerComponent : NewInvokerComponentsSet.Difference(LastInvokerComponentsSet))
		{
			ComponentChanges += "\n\t" + InvokerComponent.GetPathName() + " added";
		}
		for (const TVoxelObjectPtr<const UVoxelCollisionInvokerComponent> InvokerComponent : LastInvokerComponentsSet.Difference(NewInvokerComponentsSet))
		{
			ComponentChanges += "\n\t" + InvokerComponent.GetPathName() + " removed";
		}
	}

	LastInvokerComponents = NewInvokerComponents;
#endif

	LastInvokers = Invokers;

	ensure(Future.IsComplete());

	Future = Voxel::AsyncTask(MakeWeakPtrLambda(this, [this, Invokers = MakeSharedCopy(MoveTemp(Invokers)), ComponentChanges = MoveTemp(ComponentChanges)]
	{
		VOXEL_SCOPE_COUNTER("FVoxelCollisionInvokerView");

		const TSharedRef<TVoxelSet<FIntVector>> NewChunks = MakeShared<TVoxelSet<FIntVector>>();

		if (!FVoxelUtilities::ComputeInvokerChunks(
			*NewChunks,
			MoveTemp(*Invokers),
			LocalToWorld,
			ChunkSize,
			1024 * 1024))
		{
			VOXEL_MESSAGE(Error, "More than 1M chunks generated by collision invoker for chunk size {0}, abording", ChunkSize);
		}

		{
			VOXEL_SCOPE_LOCK(CriticalSection);

			if (!Chunks_RequiresLock)
			{
				// Initialization, don't invalidate dependency
				Chunks_RequiresLock = NewChunks;
				return;
			}

			if (NewChunks->OrderIndependentEqual(*Chunks_RequiresLock))
			{
				return;
			}

			Chunks_RequiresLock = NewChunks;
		}

		FVoxelInvalidationScope Scope(ComponentChanges);
		Dependency->Invalidate();
	}));
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

void FVoxelCollisionInvokerManager::LogInvokers()
{
	VOXEL_FUNCTION_COUNTER();
	checkVoxelSlow(IsInGameThread());

	const UWorld* World = GetWorld().Resolve();
	if (!ensure(World))
	{
		return;
	}

	LOG_VOXEL(Log, "Collision invokers for %s:", *World->GetPathName());

	for (const UVoxelCollisionInvokerComponent* Invoker : InvokerComponents)
	{
		LOG_VOXEL(Log, "\tEnabled: %s Radius: %f %s", *LexToString(Invoker->bEnabled), Invoker->Radius, *Invoker->GetPathName());
	}
}

TSharedRef<FVoxelCollisionInvokerView> FVoxelCollisionInvokerManager::MakeView(
	const int32 ChunkSize,
	const FTransform& LocalToWorld)
{
	VOXEL_FUNCTION_COUNTER();
	check(IsInGameThread());

	const TSharedRef<FVoxelCollisionInvokerView> View = MakeShared<FVoxelCollisionInvokerView>(
		ChunkSize,
		LocalToWorld);

	// Ensure the view is up to date in the first query
	{
		FVoxelTaskScope Scope(*GVoxelGlobalTaskContext);
		View->Tick(InvokerComponents);
	}

	WeakViews.Add(View);
	return View;
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

void FVoxelCollisionInvokerManager::Tick()
{
	VOXEL_FUNCTION_COUNTER();

	CheckVoxelWorlds();

	for (auto It = WeakViews.CreateIterator(); It; ++It)
	{
		const TSharedPtr<FVoxelCollisionInvokerView> View = It->Pin();
		if (!View)
		{
			It.RemoveCurrentSwap();
			continue;
		}

		View->Tick(InvokerComponents);
	}
}

void FVoxelCollisionInvokerManager::AddReferencedObjects(FReferenceCollector& Collector)
{
	VOXEL_FUNCTION_COUNTER();

	for (auto It = InvokerComponents.CreateIterator(); It; ++It)
	{
		UVoxelCollisionInvokerComponent* InvokerComponentPtr = *It;
		TObjectPtr<UVoxelCollisionInvokerComponent> InvokerComponent = ReinterpretCastRef<TObjectPtr<UVoxelCollisionInvokerComponent>>(InvokerComponentPtr);
		Collector.AddReferencedObject(InvokerComponent);

		if (!ensure(InvokerComponent))
		{
			It.RemoveCurrent();
		}
	}
}

void FVoxelCollisionInvokerManager::CheckVoxelWorlds()
{
	VOXEL_FUNCTION_COUNTER();

	TVoxelArray<FVector> Positions;
	Positions.Reserve(InvokerComponents.Num());

	for (const UVoxelCollisionInvokerComponent* InvokerComponent : InvokerComponents)
	{
		if (!InvokerComponent->bEnabled ||
			!InvokerComponent->bWaitForVoxelWorld)
		{
			continue;
		}

		Positions.Add(InvokerComponent->GetComponentLocation());
	}

	if (Positions.Num() == 0)
	{
		return;
	}

	UWorld* World = GetWorld().Resolve();
	if (!ensure(World))
	{
		return;
	}

	for (const AVoxelWorld* VoxelWorld : TActorRange<AVoxelWorld>(World))
	{
		const TSharedPtr<FVoxelRuntime> Runtime = VoxelWorld->GetRuntime();
		if (!Runtime)
		{
			continue;
		}

		const TSharedPtr<FVoxelState> State = Runtime->GetNewestState();
		if (!State ||
			State->Config->InvokerCollision.GetCollisionEnabled() == ECollisionEnabled::NoCollision)
		{
			continue;
		}

		FVoxelInvokerCollisionSubsystem& Subsystem = State->GetSubsystem<FVoxelInvokerCollisionSubsystem>();
		if (!Subsystem.HasCollision(Positions))
		{
			Subsystem.ComputeInline(*Runtime, Positions);
		}
	}
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

UVoxelCollisionInvokerComponent::UVoxelCollisionInvokerComponent()
{
	// Make sure to disable collision so that GetComponentsBoundingBox ignores us
	BodyInstance.SetCollisionEnabled(ECollisionEnabled::NoCollision);
}

void UVoxelCollisionInvokerComponent::Serialize(FArchive& Ar)
{
	Super::Serialize(Ar);

	SerializeVoxelVersion(Ar);
}

void UVoxelCollisionInvokerComponent::OnRegister()
{
	Super::OnRegister();

	const UWorld* World = GetWorld();
	if (ensure(World))
	{
		FVoxelCollisionInvokerManager::Get(World)->InvokerComponents.Add_EnsureNew(this);
	}
}

void UVoxelCollisionInvokerComponent::OnUnregister()
{
	const UWorld* World = GetWorld();
	if (ensure(World))
	{
		FVoxelCollisionInvokerManager::Get(World)->InvokerComponents.Remove_Ensure(this);
	}

	Super::OnUnregister();
}

FPrimitiveSceneProxy* UVoxelCollisionInvokerComponent::CreateSceneProxy()
{
	if (UE_BUILD_SHIPPING)
	{
		return nullptr;
	}

	class FSceneProxy final : public FPrimitiveSceneProxy
	{
	public:
		const float Radius;

		explicit FSceneProxy(const UVoxelCollisionInvokerComponent* Component)
			: FPrimitiveSceneProxy(Component)
			, Radius(Component->Radius)
		{
		}

		virtual void GetDynamicMeshElements(
			const TArray<const FSceneView*>& Views,
			const FSceneViewFamily& ViewFamily,
			const uint32 VisibilityMap,
			FMeshElementCollector& Collector) const override
		{
			VOXEL_FUNCTION_COUNTER();

			for (int32 ViewIndex = 0; ViewIndex < Views.Num(); ViewIndex++)
			{
				if (!(VisibilityMap & (1 << ViewIndex)))
				{
					continue;
				}

				FPrimitiveDrawInterface* PDI = Collector.GetPDI(ViewIndex);
				const FSceneView* View = Views[ViewIndex];
				const FMatrix LocalToWorld = GetLocalToWorld();

				const FLinearColor Color = GetViewSelectionColor(
					FColor::White,
					*View,
					IsSelected(),
					IsHovered(),
					false,
					IsIndividuallySelected());

				DrawWireSphere(
					PDI,
					LocalToWorld.GetOrigin(),
					Color,
					Radius,
					64,
					SDPG_World);
			}
		}
		virtual FPrimitiveViewRelevance GetViewRelevance(const FSceneView* View) const override
		{
			FPrimitiveViewRelevance Result;
			Result.bDrawRelevance = (!View->Family->EngineShowFlags.Game && IsSelected()) || GVoxelShowCollisionInvokers;
			Result.bDynamicRelevance = true;
			return Result;
		}
		virtual SIZE_T GetTypeHash() const override
		{
			static size_t UniquePointer;
			return reinterpret_cast<size_t>(&UniquePointer);
		}
		virtual uint32 GetMemoryFootprint() const override
		{
			return sizeof(*this) + GetAllocatedSize();
		}
	};
	return new FSceneProxy(this);
}

FBoxSphereBounds UVoxelCollisionInvokerComponent::CalcBounds(const FTransform& LocalToWorld) const
{
	return FBoxSphereBounds(FVector::ZeroVector, FVector(Radius), Radius).TransformBy(LocalToWorld);
}